# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wFmumsorjgyC4PBPbhRL3q_z8IXbFYrR
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from matplotlib.animation import FFMpegWriter
import os

# -----------------------------
# Page Config
# -----------------------------
st.set_page_config(
    page_title="For Manisha ❤️",
    layout="wide"
)

# -----------------------------
# Title
# -----------------------------
st.markdown(
    "<h1 style='text-align: center; color: crimson;'>❤️ A Special Surprise ❤️</h1>",
    unsafe_allow_html=True
)

st.markdown("<hr>", unsafe_allow_html=True)


# -----------------------------
# Name Input
# -----------------------------
name = st.text_input("✨ Enter your name:")

allowed_names = ["manisha", "manisha gupta"]


# -----------------------------
# Function to Generate Animation
# -----------------------------
@st.cache_resource
def generate_heart_video():

    def heart_equation(x, k=150):
        return np.abs(x)**(2/3) + 0.9 * np.sin(k * x) * np.sqrt(3 - x**2)

    x = np.linspace(-np.sqrt(3), np.sqrt(3), 10000)
    y = heart_equation(x)

    fig, ax = plt.subplots(figsize=(6, 4))

    ax.set_xlim(x.min(), x.max())
    ax.set_ylim(y.min() - 0.5, y.max() + 0.5)

    ax.set_title("Ooi Be By My Side Until... ❤️")
    ax.grid(True, alpha=0.3)

    line, = ax.plot([], [], color="red", linewidth=2)

    frames = 600

    def update(frame):
        i = int((frame / (frames - 1)) * len(x))
        if i == 0:
            i = 1

        line.set_data(x[:i], y[:i])
        return line,

    anim = animation.FuncAnimation(
        fig,
        update,
        frames=frames,
        interval=15,
        blit=True
    )

    writer = FFMpegWriter(fps=60)
    anim.save("heart.mp4", writer=writer)

    plt.close()

    return "heart.mp4"


# -----------------------------
# Main Logic
# -----------------------------
if name:

    if name.strip().lower() in allowed_names:

        st.success("Welcome Manisha 💖")

        # Generate video (cached)
        with st.spinner("Preparing something special for you... ❤️"):
            video_file = generate_heart_video()


        # Layout: Two Columns
        col1, col2 = st.columns(2)


        # -----------------------------
        # Left: Animation
        # -----------------------------
        with col1:
            st.subheader("💝 For You")

            if os.path.exists(video_file):
                st.video(video_file)
            else:
                st.error("Animation not found!")


        # -----------------------------
        # Right: YouTube Video
        # -----------------------------
        with col2:
            st.subheader("🎵 Your Song")

            # 👉 Replace with your favorite YouTube link
            youtube_url = "https://www.youtube.com/watch?v=JGwWNGJdvx8"

            st.video(youtube_url)


        st.markdown("<hr>", unsafe_allow_html=True)


        # -----------------------------
        # Poem Section
        # -----------------------------
        st.markdown(
            "<h2 style='text-align: center; color: #b30059;'>🌹 A Few Words From My Heart 🌹</h2>",
            unsafe_allow_html=True
        )

        poem = """
        One day you’ll ask what my heart still seeks,
        As if you never knew its silent speaks.
        Through every storm, through skies so blue,
        My only answer lives in you.
        No dream, no star, no distant view—
        All I have ever wanted is you.
        """

        st.markdown(
            f"""
            <div style="
                background-color:#fff0f5;
                padding:25px;
                border-radius:15px;
                text-align:center;
                font-size:20px;
                font-style:italic;
                color:#4d004d;
                box-shadow: 0px 0px 10px pink;
            ">
            {poem.replace('\n', '<br>')}
            </div>
            """,
            unsafe_allow_html=True
        )

        st.markdown("<br>", unsafe_allow_html=True)

        st.markdown(
            "<p style='text-align:center; font-size:18px;'>💖 Made with love, just for you 💖</p>",
            unsafe_allow_html=True
        )


    # -----------------------------
    # If Name Doesn't Match
    # -----------------------------
    else:
        st.error("Sorry, nothing for you 😄")


# -----------------------------
# Footer
# -----------------------------
st.markdown("<hr>", unsafe_allow_html=True)

st.markdown(
    "<p style='text-align:center; color:gray;'>© A Small Surprise App</p>",
    unsafe_allow_html=True
)